# Generated by Django 2.1.3 on 2018-12-19 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JioKisan', '0002_remove_phoneuser_session_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categary',
            name='id',
        ),
        migrations.AlterField(
            model_name='categary',
            name='name',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sellable',
            name='categary',
            field=models.ForeignKey(db_column='categary', on_delete=django.db.models.deletion.CASCADE, to='JioKisan.Categary'),
        ),
        migrations.AlterField(
            model_name='sellable',
            name='seller',
            field=models.ForeignKey(db_column='seller', on_delete=django.db.models.deletion.CASCADE, to='JioKisan.PhoneUser'),
        ),
    ]
