# Generated by Django 2.1.3 on 2018-12-19 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JioKisan', '0003_auto_20181219_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='categary',
            name='typ',
            field=models.ImageField(default=5, upload_to=''),
        ),
        migrations.AddField(
            model_name='phoneuser',
            name='seller',
            field=models.ImageField(default=8, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sellable',
            name='categary',
            field=models.ForeignKey(db_column='typ', on_delete=django.db.models.deletion.CASCADE, to='JioKisan.Categary'),
        ),
    ]
