# Generated by Django 2.1.3 on 2018-12-19 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JioKisan', '0004_auto_20181219_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categary',
            old_name='typ',
            new_name='cid',
        ),
        migrations.RemoveField(
            model_name='phoneuser',
            name='seller',
        ),
        migrations.AlterField(
            model_name='sellable',
            name='categary',
            field=models.ForeignKey(db_column='cid', on_delete=django.db.models.deletion.CASCADE, to='JioKisan.Categary'),
        ),
        migrations.AlterField(
            model_name='sellable',
            name='seller',
            field=models.ForeignKey(db_column='phone_number', on_delete=django.db.models.deletion.CASCADE, to='JioKisan.PhoneUser'),
        ),
    ]
